repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: mixed-line-ending
  - id: check-added-large-files
    args: ['--maxkb=500']

- repo: http://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
  - id: isort

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
  - id: black
    language_version: python3

# remove noqa's that are no longer applicable
- repo: https://github.com/asottile/yesqa
  rev: v1.2.3
  hooks:
  - id: yesqa

- repo: https://github.com/life4/flakehell
  rev: v.0.8.0
  hooks:
  - id: flakehell
    additional_dependencies: [
      "flake8-builtins",
      "pep8-naming",
      "flake8-commas",
      "flake8-comprehensions",
      "flake8-unused-arguments",
      "flake8-print",
      "flake8-todo",
      "flake8-alfred",
      # string formatting
      "flake8-pep3101",
      "flake8-string-format",
      # docstrings
      "flake8-docstrings",
      "flake8-rst-docstrings",
      "darglint",
      # pytest
      "flake8-pytest",
      # bugs
      "flake8-bugbear",
      "pandas-vet",
      "pygments"
    ]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.13.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]

- repo: https://github.com/kynan/nbstripout
  rev: 0.4.0
  hooks:
  - id: nbstripout

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy
    verbose: true
    entry: bash -c 'mypy "$@" || true' --

- repo: https://github.com/econchick/interrogate
  rev: 1.3.2
  hooks:
  - id: interrogate

- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.7.1
  hooks:
  - id: nbqa-black
    additional_dependencies: [black]
  - id: nbqa-pyupgrade
    additional_dependencies: [pyupgrade]
  - id: nbqa-isort
    additional_dependencies: [isort]

- repo: https://github.com/jendrikseipp/vulture
  rev: 'v2.3'
  hooks:
  - id: vulture
    description: find dead code

# R-related hooks
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.1.3
  hooks:
  - id: style-files
    args: [--style_pkg=styler, --style_fun=tidyverse_style]
  - id: spell-check
    files: '(.*/|)\.(Rmd|R)$'
    args: [--lang=en-US]
  - id: parsable-R
  - id: no-browser-statement
  # Checks if packages used with the pkgname::fun() syntax are listed in your DESCRIPTION file
  - id: deps-in-desc
  # A hook to run usethis::use_tidy_description() to ensure dependencies are ordered alphabetically and fields are in standard order.
  - id: use-tidy-description
  # A hook to run lintr::lint() to check that R files are lint free
  # - id: lintr
  - id: roxygenize

# bash-related hooks
- repo: https://github.com/openstack/bashate
  rev: 2.0.0
  hooks:
    - id: bashate

- repo: meta
  hooks:
  # - id: check-hooks-apply
  - id: check-useless-excludes
  # -   id: identity  # Prints all files passed to pre-commits. Debugging.
